[package]
name = "moe-extensions"
edition.workspace = true
version.workspace = true

[dependencies]
base64 = "0.22"
moe-core.workspace = true
moe-platform.workspace = true
serde.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls-native-roots"] }
serde_json.workspace = true
